version: "3"
services:
  nginx:
    build: ./nginx
    container_name: nginx 
    ports:
      - "443:443"
      - "80:80" 
    links:
      - node1
      - node2
      - node3

  node1: 
    build: ./node
    container_name: node1
    ports:
      - "8081:80"
  node2:
    build: ./node
    container_name: node2
    ports:
      - "8082:80"
  node3:
    build: ./node
    container_name: node3
    ports:
      - "8083:80" 
