# Use an official Python runtime as a parent image

FROM ubuntu:18.04

MAINTAINER jason liu  <jason.liu@sinobot.com.cn>

ENV DEBIAN_FRONTEND noninteractive


RUN apt-get update 
RUN apt-get install -y python3-dev python3-pip python3-virtualenv 
RUN pip3 install --upgrade pip setuptools


RUN pip install --upgrade pip && \
    pip install wheel &&  \
    pip install flask gunicorn


# Set the working directory to /app
WORKDIR  /app

# Copy the current directory contents into the container at /app
ADD . /app


# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python3", "app.py"]
